= Dev notes

== Publish to `.m2`

* Add `id("maven-publish")` and `id("java-gradle-plugin")` plugins

Set up plugin id
[source, groovy]
----
gradlePlugin {
    plugins {
        create("jenkins-pipeline-linter-gradle-plugin") {
            id = "me.dehasi.jenkins-pipeline-linter-gradle-plugin"
            implementationClass = "me.dehasi.jenkins.linter.Linter"
        }
    }
}
----

== Use from local `.m2`

Add to `settings.gradle.kts`
[source, groovy]
----
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
    }
}
----

Add to `build.gradle`
----
plugins {
    id 'me.dehasi.jenkins-pipeline-linter-gradle-plugin' version 'LATEST-SNAPSHOT'
}
----

== Run
----
$ gradle --quiet lint
Hello from the jenkinsfile
----

== Test
To run groovy tests add plugin `id("groovy")`.

Don't know if `testImplementation(gradleTestKit())` is needed. Test work without it.

== Parametrisation
First `project.extensions.create` then `project.tasks.register` otherwise Gradle doesn't have a chance to resolve parameters.


== Jenkins
To validate pipeline, Jenkins need `pipeline-model-definition` plugin. Official docker images goes without plugins.
I created my customised docker image with this plugin based on https://www.jenkins.io/doc/book/installing/docker/::[official instruction].

My Dockerfile (mostly copy-pasted from official instruction):

[source, dockerfile]
----
include::src/test/resources/Dockerfile[]
----

We need to turn off `setup wizard` and set password form environment variables.

[source, bash]
----
docker run --rm --detach --name myjenkins \
  --env JENKINS_OPTS='--argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin' \
  --env JAVA_OPTS='-Djenkins.install.runSetupWizard=false' \
  --publish 8080:8080 \
    myjenkins:2.361.1-1
----

Then we can call `/pipeline-model-converter/validate`.
Filename in the multipart request must be `jenkinsfile` (lowercase).

[source, bash]
----
curl --user admin:admin -X POST  -F "jenkinsfile=<jenkinsfile_valid" http://localhost:8080/pipeline-model-converter/validate
Jenkinsfile successfully validated.

curl --user admin:admin -X POST  -F "jenkinsfile=<jenkinsfile_not_valid" http://localhost:8080/pipeline-model-converter/validate
WorkflowScript: 2: Not a valid section definition: "agent". Some extra configuration is required. @ line 2, column 3.
     agent
     ^

WorkflowScript: 1: Missing required section "agent" @ line 1, column 1.
   pipeline {
   ^
----

I don't know what to do with Jenkins Crumble, it might be required.

== Java HTTP Client

`BodyPublishers.ofString` doesn't replace `\n` to `\r\n`, which also surprised me.

Boundary in multipart request can be arbitrary, I just took a nice String.

== ToDo
.todo
- [x] Maybe rename to `jenkins-pipeline-linter-gradle-plugin`
- [x] Add unit-tests
- [x] Add parametrisation
- [x] Resolve project dir for parameters
- [x] Update ignored unit-tests
- [x] Start jenkins in docker
- [x] Connect to jenkins from code
- [x] Add properties: path to jenkinsfiles.
- [x] Add properties: authorisation to jenkins, timeouts
- [x] Combine task and jenkins gateway
- [ ] Add more properties, like fail the build or not, crumble, ignore ssl, etc.
- [ ] Add an assertion that all necessary properties are set
- [ ] Check with https
- [ ] Add logging
- [ ] Find less broad name for the task, current "lint" is too broad
- [ ] *Maybe* Add jenkins as test container, extract some functional tests to unit tests maybe
- [x] *Maybe* rewrite functional tests to kotlin
- [ ] Use nice assertions, like assertj
- [ ] Use jenkins crumble
