= Dev notes

== Publish to `.m2`

* Add `id("maven-publish")` and `id("java-gradle-plugin")` plugins

Set up plugin id
[source, groovy]
----
gradlePlugin {
    plugins {
        create("jenkins-pipeline-linter-gradle-plugin") {
            id = "me.dehasi.jenkins-pipeline-linter-gradle-plugin"
            implementationClass = "me.dehasi.jenkins.linter.Linter"
        }
    }
}
----

== Use from local `.m2`

Add to `settings.gradle.kts`
[source, groovy]
----
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
    }
}
----

Add to `build.gradle`
----
plugins {
    id 'me.dehasi.jenkins-pipeline-linter-gradle-plugin' version 'LATEST-SNAPSHOT'
}
----

== Run
----
$ gradle --quiet lint
Hello from the jenkinsfile
----

== Test
To run groovy tests add plugin `id("groovy")`.

Don't know if `testImplementation(gradleTestKit())` is needed. Test work without it.

== Parametrisation
First `project.extensions.create` then `project.tasks.register` otherwise Gradle doesn't have a change to resolve parameters.

== ToDo
.todo
- [x] Maybe rename to `jenkins-pipeline-linter-gradle-plugin`
- [x] Add unit-tests
- [x] Add parametrisation
- [x] Resolve project dir for parameters
- [X] Update ignored unit-tests
- [ ] Start jenkins in docker
- [ ] Connect to jenkins
- [x] Add properties: path to jenkinsfiles.
- [ ] Add properties: authorisation to jenkins, fail the build or not, etc.
- [ ] Find less broad name for the task, current "lint" is too broad
- [ ] *Maybe* Add jenkins as test container
- [ ] *Maybe* rewrite tests to kotlin
